sonar.projectKey=Proyecto_bioterio
sonar.projectName=Sistema Integral de Gestión de Bioterios
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_470f04b877b5def22c87f4ee10d9980f51025e7f

sonar.exclusions=**/venv/**,**/migrations/**,**/static/**,**/media/**,**/__pycache__/**,**/.git/**
sonar.python.version=3.11
